// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyslvevemjrwyfuvchxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5c2x2ZXZlbWpyd3lmdXZjaHh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMDgxOTgsImV4cCI6MjA3MTg4NDE5OH0.IHlFG9xEx9JA39YrkaZVs2RC4MzzD8ofM_TyaGFNMcY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});